### ISSUE TITLE
cvv read

### ISSUE THREAD

**Issue by canerd7u** [jackbayliss/react-native-nfc-card-reader#2]
how to read card cvv with nfc

**Comment by jackbayliss** [comment]
@canerd7u  I created a sample app here: https://github.com/jackbayliss/react-native-nfc-card-reader-sample

It should be more than enough to get it working!

**Comment by canerd7u** [comment]
i clone this project and use it. No return cvv in NFC read later

**Comment by jackbayliss** [comment]
@canerd7u  Then, in this case, it's due to the card you're using - or device. I've tried this on a Samsung A40 with an English Visa / Mastercard and it reads fine.  There's not much I can offer for support other than trying the library we use : 
[https://github.com/pro100svitlo/Credit-Card-NFC-Reader](https://github.com/pro100svitlo/Credit-Card-NFC-Reader)

**Comment by canerd7u** [comment]
but you write example code 
```
NfcCardReader.startNfc(function(cardDetails){
     that.setState({cardNumber : cardDetails.cardNumber})
     that.setState({expiryDate : cardDetails.expiryDate})
     that.setState({cardType : cardDetails.cardType})

    })
```

this code not show CVV code

**Comment by jackbayliss** [comment]
@canerd7u  Sorry, my apologies.  

This library does not support CVV. And- it'd be highly insecure to do such a thing.
